name: Daily CBUAE Exchange Rates Extraction

on:
  schedule:
    # Run daily at 19:00 UTC (adjust timezone as needed)
    - cron: '0 19 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  extract-rates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create data directory
      run: mkdir -p data
      
    - name: Run CBUAE extraction
      run: |
        cd scripts
        python cbuae_extractor.py
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Commit and push changes
      run: |
        git add data/
        git diff --staged --quiet || git commit -m "Automated CBUAE rates update - $(date -u +%Y-%m-%d\ %H:%M:%S\ UTC)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
